dbhys:
  oidc:
    issuer: http://iaa.dbhys.local:5556
    client_id: dbhys-com-web
    scope: openid
    redirect_uri:
      - http://localhost:8080
    connect_timeout: 500
    read_timeout: 500

logging.level:
  com.dbhys.iaa: debug